name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  cached_network_image: ^3.3.1
  material_symbols_icons: ^4.2719.3
  flutter_screenutil: ^5.9.0
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.4
  http: ^1.2.1
  global_configs: ^1.1.2
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.1
  api_cache_manager: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/icons/
