name: {{project_name.snakeCase()}}
description: {{{description}}}
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  bloc: ^8.1.3
  cached_network_image: ^3.3.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  intl: ^0.18.1
  material_symbols_icons: ^4.2719.3

flutter:
  uses-material-design: true
  generate: true
